### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by frakman1** [arrian/lifx-python#5]
Hi Arrian,

(This is not really an issue but I had no other way to communicate this)

I just tried your excellent python library and whilst running the example_off.py script, I noticed that I would get a timeout error :

>python example_off.py
('0.0.0.0', 56700)
Traceback (most recent call last):
  File "example_off.py", line 3, in <module>
    lifx.Lifx().off()
  File "C:\Python27\lifx-python-master\lifx-python-master\lifx\lifx.py", line 11, in __init__
    self.network = Network()
  File "C:\Python27\lifx-python-master\lifx-python-master\lifx\network.py", line 27, in __init__
    self.connect()
  File "C:\Python27\lifx-python-master\lifx-python-master\lifx\network.py", line 57, in connect
    raise Exception('Handshake timed out.')
Exception: Handshake timed out.

After some experimentation, I saw that if I increased the 'timeout' variable on line 22 of network.py from 1 to 2, that it then worked perfectly.

Just wanted to share that in case others with slow networks ran into this.

**Comment by arrian** [comment]
Thanks. I've updated the timeout.

**Comment by frakman1** [comment]
marvellous! I just downloaded the new code. Thanks for incorporating it.
As one LIFX  user to another, can you tell me if you've run into this problem or not. My bulbs often drop off the network. My iOS app won't see them and reverts to the setup screen. However if I power cycle the bulbs then they happily join the network again . This makes it neigh on impossible to reliably control them and takes away any convenience I once had if I have to get up and power cycle them every time I wanted to use them. It's very frustrating and I don't know what else I can do about it. No support seems to be available via their website/FAQ or community forums. Do you have any suggestions or insight as to why they would be dropping off like that? I have several other devices on my Wifi network (embedded and otherwise) and none of them have a problem staying on.
CheersFrak

Date: Sat, 24 Jan 2015 08:00:56 -0800
